# Generated by Django 4.1 on 2022-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0002_alter_tarea_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.CharField(max_length=60),
        ),
    ]
