# Generated by Django 4.1 on 2022-09-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0005_categorias_usuarios_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
