# Generated by Django 4.1 on 2022-09-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0007_tarea_categoria_alter_tarea_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Operador',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
